import type { LucideIcon } from "lucide-react";
import {
  Anchor,
  Baby,
  Banknote,
  BarChart3,
  Bike,
  BookOpen,
  Bot,
  Briefcase,
  Brush,
  Building,
  Building2,
  Bus,
  Camera,
  Car,
  ChefHat,
  Cloud,
  Code2,
  Coffee,
  Coins,
  Cog,
  Cpu,
  CreditCard,
  Croissant,
  Dna,
  Dog,
  Dumbbell,
  Factory,
  Film,
  Fish,
  Flower2,
  Fuel,
  Gamepad2,
  Gavel,
  GraduationCap,
  Hammer,
  Handshake,
  HardHat,
  Headphones,
  HeartPulse,
  Home,
  Landmark,
  Layers,
  Leaf,
  Library,
  Lock,
  MapPin,
  Microscope,
  MonitorSmartphone,
  Music,
  Newspaper,
  Package,
  Palette,
  Palmtree,
  PawPrint,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  Recycle,
  Ruler,
  Scale,
  Scissors,
  Server,
  Shield,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Sprout,
  Stethoscope,
  Store,
  Sun,
  Syringe,
  TrainFront,
  TreePine,
  TrendingUp,
  Trophy,
  Truck,
  Users,
  UtensilsCrossed,
  Wallet,
  Warehouse,
  Wheat,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";
import { PharmacyCross } from "@/components/icons/PharmacyCross";

export type SectorIconPreset = {
  key: string;
  label: string;
  icon: LucideIcon;
};

/** Iconos disponibles al crear sectores personalizados en admin. */
export const SECTOR_ICON_PRESETS: SectorIconPreset[] = [
  // Salud y farma
  { key: "PharmacyCross", label: "Cruz de farmacia", icon: PharmacyCross },
  { key: "HeartPulse", label: "Salud / bienestar", icon: HeartPulse },
  { key: "Stethoscope", label: "Medicina / clínica", icon: Stethoscope },
  { key: "Pill", label: "Farmacia / medicamentos", icon: Pill },
  { key: "Syringe", label: "Sanitario / laboratorio", icon: Syringe },
  { key: "Microscope", label: "Investigación / lab", icon: Microscope },
  { key: "Dna", label: "Biotecnología", icon: Dna },
  { key: "Baby", label: "Infantil / puericultura", icon: Baby },

  // Tecnología y digital
  { key: "Cpu", label: "Tecnología / software", icon: Cpu },
  { key: "Code2", label: "Desarrollo / IT", icon: Code2 },
  { key: "Server", label: "Infraestructura / cloud", icon: Server },
  { key: "Cloud", label: "SaaS / cloud", icon: Cloud },
  { key: "Bot", label: "IA / automatización", icon: Bot },
  { key: "Wifi", label: "Telecomunicaciones", icon: Wifi },
  { key: "MonitorSmartphone", label: "E-commerce / apps", icon: MonitorSmartphone },
  { key: "Phone", label: "Telefonía / móvil", icon: Phone },
  { key: "Headphones", label: "Audio / medios digitales", icon: Headphones },
  { key: "Gamepad2", label: "Videojuegos / gaming", icon: Gamepad2 },

  // Finanzas y servicios profesionales
  { key: "Banknote", label: "Finanzas / banca", icon: Banknote },
  { key: "Coins", label: "Inversión / activos", icon: Coins },
  { key: "Landmark", label: "Banca / institucional", icon: Landmark },
  { key: "PiggyBank", label: "Ahorro / seguros", icon: PiggyBank },
  { key: "Wallet", label: "Pagos / fintech", icon: Wallet },
  { key: "CreditCard", label: "Medios de pago", icon: CreditCard },
  { key: "TrendingUp", label: "Crecimiento / bolsa", icon: TrendingUp },
  { key: "BarChart3", label: "Consultoría / analytics", icon: BarChart3 },
  { key: "Briefcase", label: "Servicios profesionales", icon: Briefcase },
  { key: "Handshake", label: "M&A / intermediación", icon: Handshake },
  { key: "Scale", label: "Legal / abogacía", icon: Scale },
  { key: "Gavel", label: "Jurídico / notaría", icon: Gavel },
  { key: "Users", label: "Recursos humanos", icon: Users },

  // Industria y construcción
  { key: "Factory", label: "Industria / manufactura", icon: Factory },
  { key: "Cog", label: "Maquinaria / ingeniería", icon: Cog },
  { key: "Wrench", label: "Mantenimiento / taller", icon: Wrench },
  { key: "Hammer", label: "Reformas / oficios", icon: Hammer },
  { key: "HardHat", label: "Construcción", icon: HardHat },
  { key: "Ruler", label: "Arquitectura / diseño técnico", icon: Ruler },
  { key: "Warehouse", label: "Almacén / depósito", icon: Warehouse },

  // Comercio y consumo
  { key: "ShoppingBag", label: "Retail / moda", icon: ShoppingBag },
  { key: "ShoppingCart", label: "Comercio / tienda", icon: ShoppingCart },
  { key: "Store", label: "Tienda física", icon: Store },
  { key: "Scissors", label: "Peluquería / estética", icon: Scissors },
  { key: "Sparkles", label: "Belleza / cosmética", icon: Sparkles },

  // Alimentación y hostelería
  { key: "UtensilsCrossed", label: "Hostelería / restauración", icon: UtensilsCrossed },
  { key: "ChefHat", label: "Catering / cocina", icon: ChefHat },
  { key: "Coffee", label: "Cafetería / cafés", icon: Coffee },
  { key: "Wine", label: "Bodega / vinos", icon: Wine },
  { key: "Croissant", label: "Panadería / pastelería", icon: Croissant },
  { key: "Wheat", label: "Alimentación / agroalimentario", icon: Wheat },
  { key: "Fish", label: "Pesca / marisquería", icon: Fish },

  // Logística y transporte
  { key: "Truck", label: "Logística / transporte", icon: Truck },
  { key: "Package", label: "Paquetería / mensajería", icon: Package },
  { key: "Ship", label: "Marítimo / shipping", icon: Ship },
  { key: "Anchor", label: "Puerto / náutica", icon: Anchor },
  { key: "TrainFront", label: "Ferroviario", icon: TrainFront },
  { key: "Bus", label: "Transporte de pasajeros", icon: Bus },
  { key: "Car", label: "Automoción", icon: Car },
  { key: "Bike", label: "Movilidad / bicicletas", icon: Bike },

  // Inmobiliario y edificación
  { key: "Building2", label: "Inmobiliario / oficinas", icon: Building2 },
  { key: "Building", label: "Edificios / promotora", icon: Building },
  { key: "Home", label: "Vivienda / residencial", icon: Home },

  // Educación y cultura
  { key: "GraduationCap", label: "Educación / formación", icon: GraduationCap },
  { key: "BookOpen", label: "Editorial / libros", icon: BookOpen },
  { key: "Library", label: "Academia / biblioteca", icon: Library },
  { key: "Palette", label: "Arte / diseño", icon: Palette },
  { key: "Brush", label: "Creatividad / artes", icon: Brush },
  { key: "Film", label: "Cine / audiovisual", icon: Film },
  { key: "Music", label: "Música / entretenimiento", icon: Music },
  { key: "Newspaper", label: "Medios / prensa", icon: Newspaper },
  { key: "Camera", label: "Fotografía / producción", icon: Camera },
  { key: "Trophy", label: "Deporte / eventos", icon: Trophy },
  { key: "Dumbbell", label: "Fitness / gimnasio", icon: Dumbbell },

  // Turismo y ocio
  { key: "Plane", label: "Turismo / aerolíneas", icon: Plane },
  { key: "Palmtree", label: "Ocio / resorts", icon: Palmtree },
  { key: "MapPin", label: "Viajes / destinos", icon: MapPin },

  // Energía, agro y medio ambiente
  { key: "Leaf", label: "Sostenibilidad / verde", icon: Leaf },
  { key: "Sun", label: "Solar / renovables", icon: Sun },
  { key: "Wind", label: "Eólica / energía", icon: Wind },
  { key: "Zap", label: "Electricidad / utilities", icon: Zap },
  { key: "Fuel", label: "Combustibles / petróleo", icon: Fuel },
  { key: "Recycle", label: "Reciclaje / economía circular", icon: Recycle },
  { key: "Sprout", label: "Agricultura / cultivos", icon: Sprout },
  { key: "TreePine", label: "Forestal / madera", icon: TreePine },
  { key: "Flower2", label: "Jardinería / floristería", icon: Flower2 },

  // Otros
  { key: "PawPrint", label: "Mascotas / veterinaria", icon: PawPrint },
  { key: "Dog", label: "Animales / pet care", icon: Dog },
  { key: "Shield", label: "Seguridad / vigilancia", icon: Shield },
  { key: "Lock", label: "Ciberseguridad / protección", icon: Lock },
  { key: "Layers", label: "Otros / genérico", icon: Layers },
];

export function getSectorIconPreset(key: string): SectorIconPreset | undefined {
  return SECTOR_ICON_PRESETS.find((p) => p.key === key);
}
